# Base the image on Rocky Linux (Red hat compatible)
FROM rockylinux:9
MAINTAINER Daniel Brosnan Blázquez <daniel.brosnan@deimos-space.com>

ARG FLASK_APP

RUN yum install -y epel-release

RUN yum install --allowerasing -y python3 \
    python3-pip \
    python3-tkinter \
    gcc \
    python3-devel \
    npm

RUN yum update -y
