# Base the image on centos7
FROM centos:centos7
MAINTAINER Daniel Brosnan Blázquez <daniel.brosnan@deimos-space.com>

ARG FLASK_APP
ARG HOST_USER
ARG UID_HOST_USER
ARG DATABASE_CONTAINER

USER root

RUN useradd -m -o -r -u $UID_HOST_USER $HOST_USER

RUN yum install -y epel-release

RUN yum install -y python36 \
    python36-pip \
    python36-tkinter \
    gcc \
    python36-devel \
    pytest \
    npm \
    chromium \
    chromedriver \
    centos-release-scl-rh \
    centos-release-scl \
    make \
    gcc-c++ \
    sqlite-devel \
    which \
    p7zip \
    unzip \
    less \
    cronie \
    texlive* \
    libcurl \
    libcurl-devel \
    postgresql-devel \
    postgresql

RUN yum install -y rh-ruby25 \
    rh-ruby25-rubygem-bundler \
    rh-ruby25-ruby-devel \
    rh-postgresql10-postgresql-devel

RUN pip3 install wheel \
    pytest-cov \
    termcolor \
    coverage \
    before_after \
    Sphinx \
    Flask \
    gunicorn
    
# Create folders for BOA
RUN mkdir /log
RUN mkdir /scripts
RUN mkdir /resources_path
RUN mkdir /datamodel
RUN mkdir /rboa_archive

# Create folders for ORC
RUN mkdir /orc
RUN mkdir /orc_packages
RUN mkdir /minarc_root
RUN mkdir /inputs

# Change ownership to the $HOST_USER
RUN chown $HOST_USER /log /scripts /resources_path /datamodel /rboa_archive /orc_packages /minarc_root /inputs /orc

USER $HOST_USER

# Install scripts
RUN ln -s /eboa/src/eboa/triggering/eboa_triggering.py /scripts/eboa_triggering.py
RUN ln -s /eboa/src/eboa/ingestion/eboa_ingestion.py /scripts/eboa_ingestion.py
RUN ln -s /eboa/src/rboa/triggering/rboa_triggering.py /scripts/rboa_triggering.py
RUN ln -s /eboa/src/rboa/reporting/rboa_reporting.py /scripts/rboa_reporting.py
RUN ln -s /eboa/src/sboa/scheduler/boa_scheduler.py /scripts/boa_scheduler.py
RUN ln -s /eboa/src/sboa/scheduler/boa_execute_triggering.py /scripts/boa_execute_triggering.py
RUN ln -s /vboa/src/scripts/start_flask.sh /scripts/start_flask.sh
RUN ln -s /vboa/src/scripts/start_gunicorn.sh /scripts/start_gunicorn.sh

# Environment Variables for BOA
ENV EBOA_RESOURCES_PATH /resources_path
ENV EBOA_LOG_PATH /log
ENV EBOA_SCHEMAS_PATH /eboa/src/schemas
ENV FLASK_APP $FLASK_APP
ENV FLASK_ENV development
ENV LC_ALL en_US.utf-8
ENV LANG en_US.utf-8
ENV PATH="${PATH}:/scripts"
ENV RBOA_ARCHIVE_PATH="/rboa_archive"
ENV EBOA_DDBB_HOST $DATABASE_CONTAINER
ENV SBOA_DDBB_HOST $DATABASE_CONTAINER

# expose port
EXPOSE 5000

# Environment Variables for ORC
ENV MINARC_ARCHIVE_ROOT /minarc_root
ENV MINARC_ARCHIVE_ERROR /minarc_root/.errors
ENV MINARC_DATABASE_NAME minarc_orc_db
ENV MINARC_DB_ADAPTER postgresql
ENV MINARC_DATABASE_USER minarc_orc
ENV MINARC_DATABASE_HOST $DATABASE_CONTAINER
ENV ORC_TMP /orc/tmp
ENV ORC_DATABASE_NAME minarc_orc_db
ENV ORC_DB_ADAPTER postgresql
ENV ORC_DATABASE_USER minarc_orc
ENV ORC_DATABASE_HOST $DATABASE_CONTAINER

# Copy the environment variables to a file for later use of cron
RUN declare -p | grep -Ev 'BASHOPTS|BASH_VERSINFO|EUID|PPID|SHELLOPTS|UID' > /resources_path/container.env

CMD ["/bin/bash", "-c", "/scripts/start_flask.sh"]